import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StatusBadge } from '../shared/StatusBadge';
import { PriorityBadge } from '../shared/PriorityBadge';
function formatDate(dateStr) {
    return new Date(dateStr).toLocaleString();
}
export function QueueTable({ tickets, onOpenDetail, onSort, sortField, sortDir }) {
    const SortIndicator = ({ field }) => {
        if (sortField !== field)
            return _jsx("span", { "aria-hidden": "true", children: "\u2195" });
        return _jsx("span", { "aria-hidden": "true", children: sortDir === 'asc' ? '↑' : '↓' });
    };
    return (_jsxs("table", { className: "queue-table", role: "grid", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: _jsxs("button", { onClick: () => onSort('ticketNumber'), className: "sort-btn", children: ["Ticket # ", _jsx(SortIndicator, { field: "ticketNumber" })] }) }), _jsx("th", { children: _jsxs("button", { onClick: () => onSort('createdAt'), className: "sort-btn", children: ["Created Date ", _jsx(SortIndicator, { field: "createdAt" })] }) }), _jsx("th", { children: "Summary" }), _jsx("th", { children: "Category" }), _jsx("th", { children: _jsxs("button", { onClick: () => onSort('requestedPriority'), className: "sort-btn", children: ["Req. Priority ", _jsx(SortIndicator, { field: "requestedPriority" })] }) }), _jsx("th", { children: _jsxs("button", { onClick: () => onSort('itPriority'), className: "sort-btn", children: ["IT Priority ", _jsx(SortIndicator, { field: "itPriority" })] }) }), _jsx("th", { children: _jsxs("button", { onClick: () => onSort('status'), className: "sort-btn", children: ["Status ", _jsx(SortIndicator, { field: "status" })] }) }), _jsx("th", { children: "Ticket Owner" }), _jsx("th", { children: _jsxs("button", { onClick: () => onSort('updatedAt'), className: "sort-btn", children: ["Last Updated ", _jsx(SortIndicator, { field: "updatedAt" })] }) }), _jsx("th", { children: "Action" })] }) }), _jsx("tbody", { children: tickets.map(ticket => (_jsxs("tr", { children: [_jsx("td", { children: ticket.ticketNumber }), _jsx("td", { children: formatDate(ticket.createdAt) }), _jsx("td", { className: "summary-cell", children: ticket.summary }), _jsx("td", { children: ticket.category?.name ?? '—' }), _jsx("td", { children: _jsx(PriorityBadge, { priority: ticket.requestedPriority }) }), _jsx("td", { children: ticket.itPriority ? _jsx(PriorityBadge, { priority: ticket.itPriority }) : _jsx("span", { children: "\u2014" }) }), _jsx("td", { children: _jsx(StatusBadge, { status: ticket.status }) }), _jsx("td", { children: ticket.owner?.name ?? _jsx("span", { className: "unassigned", children: "Unassigned" }) }), _jsx("td", { children: formatDate(ticket.updatedAt) }), _jsx("td", { children: _jsx("button", { onClick: () => onOpenDetail(ticket.id), className: "open-detail-btn", "aria-label": `Open detail for ticket ${ticket.ticketNumber}`, children: "Open Detail" }) })] }, ticket.id))) })] }));
}
